### ISSUE TITLE
Order problem

### ISSUE THREAD

**Issue by Alfatrick** [SpaicyGaming/UpgradablesPets#1]
Hello! 
I bought your plugin today, and when i spawn a pet with : /pet gui (example: chicken), the pet is not here, and when i type the command : /pet away, a message appears : "An onternal error occurred while attempting to perform this command" ..

**Comment by SpaicyGaming** [comment]
Sorry for the late reply, I wasn't receiving notifications from this section. You are the only person reporting me this issue.
Which spigot version are you running?
Are you still getting this error with the latest plugin version?
If the answer is yes, please provide the stacktrace.
