### ISSUE TITLE
Wrong gui item

### ISSUE THREAD

**Issue by VirtualPlanetNT** [SpaicyGaming/UpgradablesPets#10]
When I edit the path "ConfirmGui.buyItem" or "ConfirmGui.backItem" this is not saved and gives "error" when clicking.

# 
# DEFAULT
# 
#
# buyItem:
#    name: "&aBuy!"
#    lores:
#      - ""
#      - "&aClick to buy"
#
#  backItem:
#    name: "&4Cancel"
#    lores:
#      - ""
#      - "&cClick to exit"
# 
# EDITED
#
#
#

**Comment by VirtualPlanetNT** [comment]
#buyItem:
#   name: "&aComprar"
#  lores:
#      - "&7¡Haz clic para comprar!"
#
#  backItem:
#    name: "&cCancelar"
#    lores:
#      - "&7¡Haz clic para cancelar!"


Message in console: [UpgradablesPets] ERROR: Wrong stained clay item name in the confirm inventory. Please, report the issue here: https://github.com/SpaicyGaming/UpgradablesPets/issues

**Comment by SpaicyGaming** [comment]
Changes to that section require a full server restart.
Thank you for pointing it out, I'll specify it in the configuration
