### ISSUE TITLE
2 or 3 things to change

### ISSUE THREAD

**Issue by ZombieZone69** [SpaicyGaming/UpgradablesPets#11]
Hi, since my purchase of this plugin that I think has potential. I have found some little bugs and mistakes. If i can help here is a short list ;

- in the default lang_en.yml a message is missing "blacklistedWorld"
- some messages do not contain the placeholder "%currency%". example -> potEffectBought (total 3)
- changing "buyItem" or "backItem" and then reload doesn't work
- if we set the same title to the three confirmation gui the plugin can not detect the right gui

That's all I've found for now.
Good luck for this good plugin ;)

Infos :
Paper version : git-Paper-557 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Plugin version : 2.2.6-DEV

**Comment by SpaicyGaming** [comment]
Thank you for the suggestions, the next update will contain those improvements
