### ISSUE TITLE
Duplication of Pet

### ISSUE THREAD

**Issue by DjeyMute** [SpaicyGaming/UpgradablesPets#17]
Hi again,

For duplication I performed several tests.
And I found the problem.
When I have my pet next to me and I teleport to a player and the pets does not appear and so I'm doing /pet here then the pet appears but it duplicates itself to my old position

Thanks for your answer.

**Comment by DjeyMute** [comment]
I made this video to show you the bug. :)
[https://www.youtube.com/watch?v=DDsJY7f8Bq0&feature=youtu.be](url)

**Comment by SpaicyGaming** [comment]
"When I have my pet next to me and I teleport to a player and the pets do not appear", this shouldn't happen in the first place. I still think that caused by a conflict with another plugin on your server (some sort of anti-lag or mob stacker plugin). UpgradablesPets always teleport pets to their owners.

**Comment by DjeyMute** [comment]
But i have desactivate all off py plugin for the test ^^'

**Comment by SpaicyGaming** [comment]
I tried to replicate that multiple times and I couldn't. I still think that's a conflict with a plugin on your server (or a server option). No one else has ever had that problem and I can't replicate. I invite you to test the plugin on a clean server.

**Comment by DjeyMute** [comment]
But that's what I did ... no other pet plugin multiplies pets when the player teleports ...

And for this? https://www.youtube.com/watch?v=VmgsbsJJBuU&feature=youtu.be

**Comment by SpaicyGaming** [comment]
That's not possible. On my and everyone else's 1.14.4 servers the plugin works fine. I'd like to help you fix this issue but not knowing how your server is set makes it almost impossible.

What about the video?

**Comment by DjeyMute** [comment]
The pet moves in all directions and no matter how as if he was afraid
