### ISSUE TITLE
Hello I dont Check GitHub..

### ISSUE THREAD

**Issue by DerVillion** [SpaicyGaming/UpgradablesPets#21]
Hello,

Is it possible to reply on discord for me?

DerVillion#0420

I really think this is a great idea for a plugin. I want to get it but without Horses for my RPG server (should be able to ride) there is no point in getting it, if you decided to add it, send me a message on discord or just update it cause I'm following the plugin.

Thank you for your time.

Best regards,

DerVillion

**Comment by SpaicyGaming** [comment]
I'll contact you on discord
