### ISSUE TITLE
Baby pets

### ISSUE THREAD

**Issue by EvilGnome93** [SpaicyGaming/UpgradablesPets#22]
Hi There,

We're testing your plugin and it works awsome still :)
Although we do have a question.

Once baby pets are set to "true" can we make them grow in-game or not?
How does this work?

Thanks in advance for your reply!

-
Geoffrey

**Comment by SpaicyGaming** [comment]
Hi Geoffrey! 
If "MainSettings.babyPets" is set to "true", pets can't grow.
What would you want to do?

**Comment by EvilGnome93** [comment]
Ahh alrighty.
I was only wondering if the babyies were able to grow at level. But i know they wint now :)
Thanks
