### ISSUE TITLE
Ciao posso avere il tuo telegram

### ISSUE THREAD

**Issue by Distolfix** [SpaicyGaming/UpgradablesPets#24]
il tuo plugin è molto buggato vorrei segnalare anche perchè ho speso 5 euro e non vorrei buttarli, inanzitutto il pet muore con un colpo anche se aumenti la vita, con spada in diamante posso uccidere il mio stesso pet; i soldi non li prende se cambio pet

**Comment by SpaicyGaming** [comment]
Ciao,
se il pet muore con un colpo di di spada significa che la vita del pet e' minore o uguale al danno causato dalla spada. Per evitare che un pet muoia con un solo colpo, la vita del pet deve essere maggiore del danno. I vari valori della vita sono configurabili dal file di configurazione _config.yml_. Puoi verificare la vita del pet tramite il comando _/pet info_ o tramite l'info item (il foglio di carta) nella GUI principale.
Il cambio del pet non prevede nessun prelievo di soldi. Viene semplicemente cambiato il tipo del pet, tutti gli upgrades rimangono. Se invece il pet viene cancellato (tramite il comando _/pet delete <player>_), tutti gli upgrades vengono cancellati e il player dovra' ricomprare il pet.
Visto l'interesse, nella prossima release aggiungero' la possibilita' di addebitare una commissione quando il pet viene cambiato.

Tutto cio' e' descritto nella documentazione del plugin.

Chiudo la issue. Se avessi bisogno di altri chiarimenti puoi contattarmi su telegram: @SpaicyG
