### ISSUE TITLE
Hi have 3 suggestions! :D

### ISSUE THREAD

**Issue by Scrulius** [SpaicyGaming/UpgradablesPets#26]
Hi Spaicy, i have 3 suggestions:

- Add support to [tokenmanager](https://www.spigotmc.org/resources/tokenmanager.8610/) (Tokenenchants its a premium plugin and dont works anymore)

- A pet riding option

- More mobs and potion effects

¡Thank you!

**Comment by michelecoco** [comment]
Thank you for the suggestions! 
I'll probably add some of those features in the next releases.
