### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Distolfix** [SpaicyGaming/UpgradablesPets#27]
Problema con WildStacker. Il plug-in con WildStacker fa conflitto 

Se viene colpito il pet con spada puoi hittare il tuo stesso pet, se gli aumenti la vita non ha effetto. 

Modificando il config.yml disabilitando il mob stacking ritorna a funzionare, quindi penso vada in conflitto con un plugin mobstack. Attendo tuoi aggiornamenti e un update risolutivo .

Versione server 1.8.8 PaperSpigot
Versione plugin: ultima uscita 
Versione WildStacker ultima uscita. 

https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-wildstacker-%E2%9A%A1%EF%B8%8F-spawners-entities-drops-blocks-%E2%9A%A1%EF%B8%8F-spawner-upgrades.87404/

**Comment by michelecoco** [comment]
Il problema segnalato non e' causato da UpgradablesPets.
Il plugin WildStacker non e' contenuto nell'elenco dei plugins esplicitamente supportati da UpgradablesPets. Per questo motivo non bisogna supporre che UpgradablesPets sia compatibile con esso.

In ogni caso il problema puo' essere risolto configurando correttamente WildStacker. Bisognerebbe disabilitare lo stacking di entita' con nomi
