### ISSUE TITLE
¡More suggestions!

### ISSUE THREAD

**Issue by Scrulius** [SpaicyGaming/UpgradablesPets#28]
Thank you for add tokenmanager support ^-^

I have more suggestions (I'm sorry to be a bore)

- Option to enable/disable potion effect, example: (Right click on the effect to disable invisibility)

- Cosmetic trails to the pet (Maybe it is very difficult, but it would be incredible)

- Discord server, this would make your community grow and your plugin would become more popular

And thank you Spaicy for your work, this plugin its fucking amazing 😎

**Comment by michelecoco** [comment]
Thank you for all the suggestions!
