### ISSUE TITLE
Can still buy potion effects after disabling

### ISSUE THREAD

**Issue by DrkMatr1984** [SpaicyGaming/UpgradablesPets#4]
So, I've disabled invisibility in the config, and I am still able to buy it. Moreover, I deleted some levels from some of the other potion effects, and you can still upgrade to those higher levels. Here is a copy of my current config (renamed to .txt for uploading). I'm using the latest version of the plugin, and the latest spigot. 
[config.txt](https://github.com/SpaicyGaming/UpgradablesPets/files/1920642/config.txt)

**Comment by SpaicyGaming** [comment]
Thank you for reporting!
This is definitely a bug. I'll fix it in the next release!

**Comment by SpaicyGaming** [comment]
I've just release a new version. 
If there are any issues feel free to reopen the ticket!
