### ISSUE TITLE
Problem with "New Update" and /give

### ISSUE THREAD

**Issue by DjeyMute** [SpaicyGaming/UpgradablesPets#6]
Hello,
For the firt problem, I installed the latest version 2.2.0 but the plugins when i connect on my server tells me that I'm still in 2.1.0
The second problem, for the command /give I wanted to be able to give pet from my site but it does not work. I can just give pet in the game

**Comment by SpaicyGaming** [comment]
Hello, 
don't worry about the plugin version, I forgot to change a digit.
Currently, the "/give" command can only be executed by players. I can make it executable also by the console. I'll release an update in a few hours.

**Comment by DjeyMute** [comment]
Okey ! Thanks for all !
By the way if you want to add an option "updater: true or false"
It would be perfect ;)

**Comment by SpaicyGaming** [comment]
Features have been added in the release [2.2.1-DEV](https://www.spigotmc.org/resources/upgradablespets-1-7-1-13-x-mysql-mongodb-levels-guis-effects.46406/update?update=264832)

Can I see the sign content?

**Comment by DjeyMute** [comment]
Thk and take that : https://image.noelshack.com/fichiers/2019/07/2/1550012095-capture-d-ecran-93.png

**Comment by DjeyMute** [comment]
Thank's for the maj men ! 
See you next time and again thanks for your responsiveness

**Comment by SpaicyGaming** [comment]
The problem has been fixed in version [2.2.2-DEV](https://www.spigotmc.org/resources/upgradablespets-1-7-1-13-x-mysql-mongodb-levels-guis-effects.46406/update?update=264910)

Thank you for reporting
