### ISSUE TITLE
Can't buy any upgrades

### ISSUE THREAD

**Issue by Nekomitsuki** [SpaicyGaming/UpgradablesPets#8]
There is currently bug, that won't let you upgrade anything to pet related. I can buy pet but can't upgrade anything (Potion Effect or Max Health).
I have enough money to afford upgrade and it doesn't seem problem with my config since this is the only thing that don't work and it doesn't work after config reset.

Exception stack trace: https://hastebin.com/rerawejosi.sql
Screenshot: https://i.imgur.com/wSLahGU.png
Version: git-Paper-530 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Plugin version: 2.2.5-DEV

**Comment by SpaicyGaming** [comment]
Can I see your configuration file?

**Comment by Nekomitsuki** [comment]
Here you go.
config.yml: https://hastebin.com/epahukeriv.coffeescript
lang_en: https://hastebin.com/ibolefivow.pl

**Comment by Nekomitsuki** [comment]
In case you want the file...

[config.zip](https://github.com/SpaicyGaming/UpgradablesPets/files/2927473/config.zip)

**Comment by SpaicyGaming** [comment]
Thank you for reporting. The issue has been fixed in version [2.2.6-DEV](https://www.spigotmc.org/resources/upgradablespets-1-7-1-13-x-mysql-mongodb-levels-guis-effects.46406/update?update=267565)
