### ISSUE TITLE
Wrong pet name location

### ISSUE THREAD

**Issue by VirtualPlanetNT** [SpaicyGaming/UpgradablesPets#9]
When the pet is a baby, the name's inside
![sin titulo](https://user-images.githubusercontent.com/43713563/53828792-ec09b880-3f7e-11e9-8399-af6d9658dc98.png)

**Comment by SpaicyGaming** [comment]
Which minecraft version is the server running? Can I see the output of "/ver"?

**Comment by VirtualPlanetNT** [comment]
[19:34:57 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by SpaicyGaming** [comment]
I think that's caused by one of your mod. The plugin uses Minecraft vanilla nametags, it doesn't change any position.

![cow](https://i.imgur.com/fYVbLsN.png)

**Comment by VirtualPlanetNT** [comment]
Mmmm maybe, although the other mobs are fine.
